twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        fos_csrf_provider: "@security.csrf.token_manager"

when@test:
    twig:
        strict_variables: true
